### ISSUE TITLE
cookie失效&谷歌检测到cookie异常

### ISSUE THREAD

**Issue by wayne3602** [easychen/CookieCloud#12]
# 使用的浏览器  
上传数据的浏览器为edge  
接收数据的浏览器为chrome

# 部署方式
docker

# 问题描述
每次重启计算机打开浏览器就会发现cookie失效（chrome的谷歌账号也被退出了，即右上角头像显示已暂停），需要手动同步一次才行，并且使用谷歌登录的时候提示“谷歌检测到您的cookie存在异常”。

**Comment by easychen** [comment]
Google等大厂有Cookie以外的风控验证，光同步Cookie会报错，因此不建议使用CookieCloud同步。
