### ISSUE TITLE
是否能提供个ESM Node的例子？

### ISSUE THREAD

**Issue by gouku** [easychen/CookieCloud#15]
https://github.com/easychen/CookieCloud/blob/master/examples/playwright/tests/example.spec.js 这个例子中用到的crypto-js不支持ESM，我这边有个现成的项目无法集成，不知道有没有什么替代方案，或者现成的ESM写法的例子。

**Comment by easychen** [comment]
crypto-js本身支持ESM的吧  https://github.com/easychen/CookieCloud/blob/master/extension/function.js#L152
