### ISSUE TITLE
请问服务端保存的数据不会持久化吗

### ISSUE THREAD

**Issue by huluohu** [easychen/CookieCloud#16]
如题，因为看docker启动时没指定挂载目录，想了解下服务端接收到的数据都是内存保存吗，重启应用数据会不会丢失？谢谢。

**Comment by easychen** [comment]
会写到容器的目录下，容器被回收后会丢失。Cookie数据本来就会过期，因此不应该长时间保留旧数据。

**Comment by huluohu** [comment]
> 会写到容器的目录下，容器被回收后会丢失。Cookie数据本来就会过期，因此不应该长时间保留旧数据。

了解了，感谢。
