### ISSUE TITLE
请问能通过docker改默认端口和默认页面的显示信息吗？

### ISSUE THREAD

**Issue by Mrxlei** [easychen/CookieCloud#21]
请问能通过docker改默认端口和默认页面的显示信息吗？
能的话怎么设置？

**Comment by Mrxlei** [comment]
Fetch API cannot load nastool.cn:8088/update. URL scheme "nastool.cn" is not supported.
ver：0.21

**Comment by easychen** [comment]
① 不能
② 加 http:// 前缀

**Comment by werran2** [comment]
> ① 不能 ② 加 http:// 前缀

和威联通自带的Virtualizition Station端口冲突
威联通就不能装了吗
