### ISSUE TITLE
24小时不重复上传这个逻辑不会生效。

### ISSUE THREAD

**Issue by kingname** [easychen/CookieCloud#37]
https://github.com/easychen/CookieCloud/blob/631698d4493bf6d372dcc20236bd81554e2ea55b/extension/function.js#L187

SHA256算法，在相同明文的情况下，每次生成的密文都不一样。这就导致这一行代码`last_uploaded_info.sha256 === sha256`永远是false。

**Comment by easychen** [comment]
sha256是散列算法，类似MD5，结果应该是确定的吧。https://zh.wikipedia.org/wiki/SHA%E5%AE%B6%E6%97%8F

**Comment by kingname** [comment]
你说的没错，我搞错了。
