### ISSUE TITLE
docker部署可以支持数据本地存储映射出来么

### ISSUE THREAD

**Issue by loveu5522** [easychen/CookieCloud#39]
因为docker-compose 部署同一个项目经常重建，这就导致已经同步的cookie丢失，可以支持数据本地存储持久化么。

**Comment by easychen** [comment]
你可以自己用 -v 命令挂载出来， 目录是 /data/api/data 。不过Cookie本来就是临时数据，没什么必要。

**Comment by loveu5522** [comment]
好的，谢谢
