### ISSUE TITLE
English chrome plugin?

### ISSUE THREAD

**Issue by Paradoxum** [easychen/CookieCloud#43]
![image](https://github.com/easychen/CookieCloud/assets/6451395/d7378518-7983-4d95-8714-7875ac691920)

![image](https://github.com/easychen/CookieCloud/assets/6451395/af3353b1-fc7a-4fd1-9d0a-0acd9fbf63f0)

What's each field for for setting up?

**Comment by Paradoxum** [comment]
![image](https://github.com/easychen/CookieCloud/assets/6451395/85e3e065-f4f7-4adc-ab0a-51865e92f1d4)


![image](https://github.com/easychen/CookieCloud/assets/6451395/4d5e626a-ef93-4315-a8f4-256d699cf90c)


here.

**Comment by Paradoxum** [comment]
After installing docker I have no idea what to do next :( 

![image](https://github.com/easychen/CookieCloud/assets/6451395/de35c708-8f90-440b-b1fd-3e000853cf7b)

Any help? Thank you.

**Comment by wuwb** [comment]
change '服务器地址' to your service in the docker

**Comment by easychen** [comment]
Add english language in 0.2.3
