### ISSUE TITLE
请问是不是不支持Arc浏览器？

### ISSUE THREAD

**Issue by itangqiao** [easychen/CookieCloud#44]
点击测试和同步都没有任何回应~

**Comment by easychen** [comment]
首页有写：

![image](https://github.com/easychen/CookieCloud/assets/1294760/32f75747-b71c-4e82-8a72-a112be559fe9)

**Comment by chenyucheng0503** [comment]
不知道 Arc 需要做什么适配，现在Arc已经是主力浏览器了

**Comment by lewwang** [comment]
> 点击测试和同步都没有任何回应~

@itangqiao 我这里是完美支持ARC...

**Comment by Mrered** [comment]
> 点击测试和同步都没有任何回应~

和你情况一样
