### ISSUE TITLE
CookieCloud同步后退出浏览器cookie就是失效

### ISSUE THREAD

**Issue by zengjiu** [easychen/CookieCloud#51]
CookieCloud同步后退出浏览器cookie就是失效，发现CookieCloud同步覆盖浏览器是session默认=true导致退出就失效，希望增加选项，或者默认改为false

**Comment by DavEo8I8** [comment]
同樣的問題，希望可以得到解決

**Comment by gianozdp** [comment]
是啊，每次都要重新登陆，这样意义 真的不是很大

**Comment by easychen** [comment]
最新版添加了一个指定Cookie过期时间的设置。

![image](https://github.com/easychen/CookieCloud/assets/1294760/53b1c46c-a65f-4c39-a87f-b16e8c7e1f8e)

**Comment by gianozdp** [comment]
还没有发布最新release吧楼主，不会自己编译啊

**Comment by easychen** [comment]
> 还没有发布最新release吧楼主，不会自己编译啊

商店审核需要时间
