### ISSUE TITLE
我希望提供我自己部署的服务

### ISSUE THREAD

**Issue by YeTianXingShi** [easychen/CookieCloud#54]
https://cookiecloud.zhensnow.uk/

服务器在美国 走了cf代理。

**Comment by easychen** [comment]
已经添加到首页，感谢分享。

**Comment by siren202101** [comment]
> https://cookiecloud.zhensnow.uk/
> 
> 服务器在美国 走了cf代理。

大佬，为什么我用CF代理CDN后就无法上传了？
你是如何办到的？
