### ISSUE TITLE
用api调用的时候，uuid在哪里获取啊？

### ISSUE THREAD

**Issue by xushier** [easychen/CookieCloud#56]
用api调用的时候，uuid在哪里获取啊？

**Comment by easychen** [comment]
插件自动生成的，要手动传进去

**Comment by xushier** [comment]
浏览器插件嘛？浏览器插件只有用户key和端到端密码呀，uuid是在哪里看呢？
![image](https://github.com/easychen/CookieCloud/assets/31540107/0a50e837-ced3-4702-b6ec-1238a9dfdf67)

**Comment by Chgocn** [comment]
用户Key就是 uuid, 端对端加密密码就是 password

**Comment by xushier** [comment]
> 用户Key就是 uuid, 端对端加密密码就是 password

但是从 pythton 的 PyCookieCloud 模块的演示代码来看是不一样的呀，而且实际测试，填写之后，也确实返回获取不到key。
![image](https://github.com/easychen/CookieCloud/assets/31540107/22aad63d-430f-4aad-b41e-fb973b1bc7db)
