### ISSUE TITLE
【求助】JD获取Cookie问题

### ISSUE THREAD

**Issue by cyk2018** [easychen/CookieCloud#72]
看了一下，JD网页端好像账号密码登录有其他额外验证操作，验证码登录也会检测到异常行为（青龙面板）然后强制下线，这种情况下是不是没法用CookieCloud自动获取Cookie，不知道有没有老哥搞过这个。

**Comment by easychen** [comment]
CookieCloud 不是用来获取Cookie的，它只是 Cookie 同步工具。
