### ISSUE TITLE
视频网站下载视频能否调用Cookie？

### ISSUE THREAD

**Issue by WorkersPages** [easychen/CookieCloud#77]
有一个很好的下载网站视频项目 https://github.com/alexta69/metube
但有些网站需要登录才能下载，能否调用此项目生成的Cookie，或都说，可能 生成不加密的的Cookie保存成Cookie.txt文件

**Comment by easychen** [comment]
自己写脚本调用api，然后按其要求生成就行了。https://github.com/easychen/CookieCloud/blob/master/README_cn.md#api-%E6%8E%A5%E5%8F%A3

**Comment by WorkersPages** [comment]
> 自己写脚本调用api，然后按其要求生成就行了。https://github.com/easychen/CookieCloud/blob/master/README_cn.md#api-%E6%8E%A5%E5%8F%A3

这可能对我来说有点困难，毕竟我不懂代码，我不是程序员。
不过，有一个老哥写了个方法 [https://github.com/alexta69/metube/issues/418](https://github.com/alexta69/metube/issues/418)  但我试了几次，服务可以运行起来。但浏览器插件连不上服务端。
