### ISSUE TITLE
CookieCloud同步失败：cookie解密失败

### ISSUE THREAD

**Issue by HomeQi** [easychen/CookieCloud#79]
【ERROR】2024-08-23 09:29:40,813 - site.py - CookieCloud同步失败：cookie解密失败：'utf-8' codec can't decode byte 0xe0 in position 0: invalid continuation byte
【INFO】2024-08-23 09:29:40,803 - site.py - 开始同步CookieCloud站点 ...

请教一下这个是什么原因？谢谢

**Comment by Hyphen-H** [comment]
我尝试了公用cookiecloud api和我的vps docker自建cookiecloud都提示同样问题。。

已成功，把端对端更改成了简单密码。。
