### ISSUE TITLE
localstorage在默认情况下会不同步

### ISSUE THREAD

**Issue by WingGao** [easychen/CookieCloud#80]
https://github.com/easychen/CookieCloud/blob/be3466562e3e4070810572385232166fe397c9c8/extension/function.js#L313-L332

默认`domains=[]`, 会导致`ret_storage={}`直接就返回了。这个应该要返回`local_storages`。

**Comment by easychen** [comment]
这里我记得是故意改成这样的，因为个别站点的 localstorage 可能非常大（有的用它缓存文档），全部域名都同步用一段时间后容易出现性能问题。
